104 陈益振 第1课作业
Guigulive/Team-K pull request #3
Opened 2018-03-11 15:19 UTC by jonkiky

2018-03-13 03:23 UTC, minzhi3 requested changes

2018-03-13 03:23 UTC, minzhi3 commented on Lesson-1/assignment/yours.sol
> +    address frank ;
这个合约应该有两个地址，frank和员工。实现frank添加员工，员工领工资这一过程。

2018-03-13 03:23 UTC, minzhi3 commented on Lesson-1/assignment/yours.sol
> +     function setAddress(address newAddress){
修改地址时应该先验证身份msg.sender == frank，另外这里是修改员工地址而不是frank地址

2018-03-13 03:23 UTC, minzhi3 commented on Lesson-1/assignment/yours.sol
> +    function setSalary(uint money){
同样修改工资时也要验证身份，不然随便谁都能改工资了

2018-03-13 03:23 UTC, minzhi3 commented on Lesson-1/assignment/yours.sol
> +        uint nextPayDay = lastPayDay +payrollDuraton ;
geiPaid员工领工资而不是frank领工资
另外注意验证员工身份

2018-03-26 05:33 UTC, minzhi3 requested changes
单元测试还需要改改，可以参考其他同学的代码

2018-03-26 05:33 UTC, minzhi3 commented on Lesson-4/assignment/test/Payroll.js
> +                            assert.equal(employee,accounts[0])
既然已经remove了，地址应该是变成0x0000000000000000000000000000000000000000才对

2018-03-26 05:33 UTC, minzhi3 commented on Lesson-4/assignment/test/Payroll.js
> +        it(" Remove employee",function(){
测remove需要先addemployer不然会出错

2018-03-26 05:33 UTC, minzhi3 commented on Lesson-4/assignment/test/Payroll.js
> +                        instance.removeEmployee(accounts[0])
只测add的话这里不需要remove操作

2018-03-26 05:36 UTC, minzhi3 commented
另外第三课作业还没交，没上传？

2018-03-31 08:34 UTC, minzhi3 requested changes
Lesson-5/assignment/payroll.zip 这个文件是空的？
你看下是不是没传上来

2018-03-31 12:24 UTC, jonkiky commented
Sorry, I used the wrong command to zip file.  I have pushed files . Please check it out.

2018-03-31 14:49 UTC, minzhi3 approved these changes
node_modules和build文件夹不用传上来，是自动生成的文件

2018-03-31 14:50 UTC, merged