102 丰寅峰 第五课作业
Guigulive/Team-K pull request #50
Opened 2018-03-28 13:53 UTC by PeerlessFYF

@minzhi3

2018-03-31 08:49 UTC, minzhi3 requested changes
zip文件夹里的components并没有实现，再确认一下是不是传错了

2018-03-31 13:41 UTC, PeerlessFYF commented
@minzhi3 github上下载下来确实打不开，我重新传文件了，麻烦merge一下。

2018-03-31 14:43 UTC, minzhi3 requested changes
几个函数的实现补一下

2018-03-31 14:43 UTC, minzhi3 commented on Lesson-5/assignment/payroll/src/components/EmployeeList.js
> +  loadEmployees(employeeCount) {
loadEmployees，addEmployee，updateEmployee，removeEmployee   这几个方法没实现出来，交错文件了？

2018-03-31 14:43 UTC, minzhi3 commented on Lesson-5/assignment/payroll/src/components/Employee.js
> +  checkEmployee = () => {
checkEmployee ，getPaid 也没写出来

2018-03-31 15:46 UTC, PeerlessFYF commented
@minzhi3 这2个文件重传

2018-04-01 01:47 UTC, PeerlessFYF commented
@minzhi3 第六课就上传了核心的代码文件

2018-04-06 08:04 UTC, minzhi3 approved these changes

2018-04-06 08:04 UTC, merged